name: filcnaplo_desktop_ui
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Filcnaplo main dep
  filcnaplo:
    path: ../filcnaplo/
  filcnaplo_kreta_api:
    path: ../filcnaplo_kreta_api/

  cupertino_icons: ^1.0.2
  flutter_feather_icons: ^2.0.0+1
  provider: ^5.0.0
  url_launcher: ^6.0.9
  flutter_linkify: ^5.0.2
  flutter_markdown: ^0.6.5
  animations: ^2.0.1
  confetti: ^0.6.0
  auto_size_text: ^3.0.0
  flutter_acrylic: ^1.1.3
  elegant_notification: ^1.6.1
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
