name: refilc_mobile_ui
publish_to: "none"

environment:
  sdk: ">=3.3.2 <=3.6.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # reFilc Main
  refilc:
    path: ../refilc/
  # e-KRETA API (kreten) client
  refilc_kreta_api:
    path: ../refilc_kreta_api/
  # reFilc Plus
  refilc_plus:
    path: ../refilc_plus/

  flutter_feather_icons: ^2.0.0+1
  provider: ^6.1.1
  fl_chart: ^0.68.0
  url_launcher: ^6.2.5
  flutter_material_color_picker: ^1.1.0+2
  photo_view: ^0.15.0
  flutter_linkify: ^6.0.0
  flutter_custom_tabs: ^2.0.0+1
  flutter_markdown: ^0.7.2+1
  animations: ^2.0.11
  animated_list_plus: ^0.5.0
  confetti: ^0.7.0
  # live_activities: ^1.9.1+1
  animated_flip_counter: ^0.3.4
  lottie: ^3.1.0
  rive: ^0.12.4
  animated_background: ^2.0.0
  home_widget:
    git:
      url: https://github.com/refilc/home_widget.git
      ref: flutter-beta
  dropdown_button2: ^2.3.9
  flutter_svg: ^2.0.10+1
  background_fetch: ^1.2.2
  wtf_sliding_sheet: ^1.0.0
  package_info_plus: ^8.0.0
  dotted_border: ^2.0.0+3
  screenshot: ^3.0.0
  image_gallery_saver: ^2.0.2
  rounded_expansion_tile:
    git:
      url: https://github.com/kimaah/rounded_expansion_tile.git
  # go_router: ^14.2.0
  flutter_expandable_fab: ^2.0.0
  intl: ^0.19.0
  i18n_extension: ^12.0.1
  auto_size_text: ^3.0.0
  connectivity_plus: ^6.0.3
  collection: ^1.18.0
  share_plus: ^10.0.3
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  image_crop_plus: ^1.0.0
  uuid: ^4.3.3
  maps_launcher: ^2.2.0
  google_fonts: ^6.1.0
  # flutter_any_logo: ^1.1.1
  custom_sliding_segmented_control: ^1.8.1
  get_it: ^7.6.7
  xml: ^6.5.0
  markdown: ^7.2.2
  carousel_slider: ^5.0.0
  flutter_portal: ^1.1.4
  webview_flutter: ^4.8.0
  file_picker: ^8.0.5
  shake_flutter: ^17.0.0
  qr_code_scanner_plus: ^2.0.6
  
dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
