name: refilc
description: "Egy nem hivatalos e-KRÉTA kliens, diákoktól diákoknak."
homepage: https://refilc.hu
publish_to: "none"

version: 5.0.0+244

environment:
  sdk: ">=2.17.0 <=3.3.2"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # reFilc packages
  refilc_mobile_ui:
    path: "../refilc_mobile_ui/"
  refilc_desktop_ui:
    path: "../refilc_desktop_ui/"
  refilc_kreta_api:
    path: "../refilc_kreta_api/"
  refilc_plus:
    path: "../refilc_plus"

  flutter_localizations:
    sdk: flutter
  i18n_extension: ^11.0.11
  sqflite: ^2.2.0+2
  intl: ^0.18.1
  provider: ^6.1.1
  http: ^1.1.2
  uuid: ^4.2.1
  html: ^0.15.0
  open_filex: ^4.3.4
  # open_file:
  #   git:
  #     url: https://github.com/crazecoder/open_file
  #     ref: master
  path_provider: ^2.0.2
  permission_handler: ^11.0.1
  share_plus: ^7.0.2
  connectivity_plus: ^5.0.2
  flutter_displaymode: ^0.6.0
  quick_actions: ^1.0.1
  animated_list_plus: ^0.5.0
  dynamic_color: ^1.2.2
  material_color_utilities: ^0.8.0
  crypto: ^3.0.2
  elegant_notification: ^1.6.1
  flutter_feather_icons: ^2.0.0+1
  live_activities: ^1.7.4
  animated_flip_counter: ^0.2.5
  lottie: ^3.1.0
  rive: ^0.12.4
  animated_background: ^2.0.0
  dropdown_button2: ^2.3.9
  home_widget: ^0.4.1
  flutter_expandable_fab: ^2.0.0
  uni_links: ^0.5.1
  url_launcher: ^6.1.6
  workmanager: ^0.5.1
  flutter_svg: ^2.0.10+1
  image_picker: ^1.0.7
  animations: ^2.0.1
  background_fetch: ^1.1.5
  flutter_local_notifications: ^16.2.0
  package_info_plus: ^5.0.1
  screenshot: ^2.1.0
  flutter_staggered_grid_view: ^0.7.0
  sqflite_common_ffi_web: ^0.4.0
  image_crop:
    git:
      url: https://github.com/kimaah/image_crop.git
  googleapis: ^12.0.0
  google_sign_in: ^6.2.1
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  maps_launcher: ^2.2.0
  google_fonts: ^6.1.0
  flutter_stripe: ^10.0.0
  get_it: ^7.6.7
  xml: ^6.5.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: "^2.3.10"
  sqflite_common_ffi: ^2.0.0+3

flutter:
  uses-material-design: true

  assets:
    - assets/icons/ic_launcher.png
    - assets/icons/ic_splash.png
    - assets/icons/ic_rounded.png
    - assets/animations/
    - assets/images/
    - assets/images/subject_covers/
    - assets/launch_icons/
    - assets/images/ext_logo/
    - assets/svg/menu_icons/
    - assets/other/dirtywords.xml
    - assets/svg/mesh_bg.svg

  fonts:
    - family: FilcIcons
      fonts:
        - asset: assets/fonts/FilcIcons.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic

    # - family: SpaceMono
    #   fonts:
    #     - asset: assets/fonts/SpaceMono/SpaceMono-Regular.ttf
    #     - asset: assets/fonts/SpaceMono/SpaceMono-Bold.ttf
    #       weight: 700
    #     - asset: assets/fonts/SpaceMono/SpaceMono-Italic.ttf
    #       style: italic
    #     - asset: assets/fonts/SpaceMono/SpaceMono-BoldItalic.ttf
    #       weight: 700
    #       style: italic
    - family: GeistMono
      fonts:
        - asset: assets/fonts/GeistMono/GeistMono-Regular.otf
          weight: 500



flutter_launcher_icons:
  image_path: assets/icons/ic_android.png
  android: true
  adaptive_icon_background: "#3D7BF4"
  adaptive_icon_foreground: assets/icons/ic_android.png
  ios: false
  remove_alpha_ios: false

flutter_native_splash:
  color: "#3D7BF4"
  image: assets/icons/ic_splash.png
  android_12:
    image: assets/icons/ic_splash.png
  android: true
  android_gravity: center
  ios: true
  ios_content_mode: center
  web: false
