name: filcnaplo_kreta_api
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  filcnaplo:
    path: ../filcnaplo/
  http: ^0.13.3
  provider: ^5.0.0
  file_picker: ^6.1.1
  intl: ^0.18.1
  i18n_extension: ^10.0.1
  uuid: ^4.2.1

dev_dependencies:
  flutter_lints: ^3.0.1
