name: filcnaplo_premium
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Filcnaplo main dep
  filcnaplo:
    path: ../filcnaplo/
  filcnaplo_kreta_api:
    path: ../filcnaplo_kreta_api/
  filcnaplo_mobile_ui:
    path: "../filcnaplo_mobile_ui/"

  provider: ^5.0.0
  flutter_feather_icons: ^2.0.0+1
  uni_links: ^0.5.1
  url_launcher: ^6.1.6
  dropdown_button2: ^1.8.9
  home_widget: ^0.1.6
  image_picker: ^0.8.6
  image_crop:
    git:
      url: https://github.com/kimaah/image_crop.git
  lottie: ^1.4.3
  animations: ^2.0.1
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
