name: filcnaplo_mobile_ui
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Filcnaplo main dep
  filcnaplo:
    path: ../filcnaplo/
  filcnaplo_kreta_api:
    path: ../filcnaplo_kreta_api/
  filcnaplo_premium:
    path: ../filcnaplo_premium/

  flutter_feather_icons: ^2.0.0+1
  provider: ^5.0.0
  fl_chart: ^0.45.1
  url_launcher: ^6.0.9
  flutter_material_color_picker: ^1.1.0+2
  photo_view: ^0.14.0
  flutter_linkify: ^5.0.2
  flutter_custom_tabs: ^1.0.3
  flutter_markdown: ^0.6.5
  animations: ^2.0.1
  animated_list_plus: ^0.5.0
  confetti: ^0.6.0
  live_activities: ^1.0.0
  animated_flip_counter: ^0.2.5
  lottie: ^1.4.3
  rive: ^0.9.1
  animated_background: ^2.0.0
  home_widget: ^0.1.6
  dropdown_button2: ^1.8.9
  flutter_svg: ^1.1.6
  background_fetch: ^1.1.5
  wtf_sliding_sheet: ^1.0.0
  package_info_plus: ^4.0.2
  dotted_border: ^2.0.0+3
  screenshot: ^2.1.0
  image_gallery_saver: ^2.0.2
  rounded_expansion_tile:
    git:
      url: https://github.com/kimaah/rounded_expansion_tile.git
  go_router: ^12.1.3
  flutter_expandable_fab: ^2.0.0
  intl: ^0.18.1
  i18n_extension: ^10.0.1
  auto_size_text: ^3.0.0
  connectivity_plus: ^5.0.2
  collection: ^1.18.0
  share_plus: ^7.2.1
  image_picker: ^0.8.9
  path_provider: ^2.1.1
  image_crop:
    git:
      url: https://github.com/kimaah/image_crop.git
  
dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true